// const SERVER_CLIENT_PORT    = '80/wscobranza'
// const SERVER_CLIENT_IP      = 'http://172.16.214.57'
const SERVER_CLIENT_PORT 	= '1707'
const SERVER_CLIENT_IP 		= 'http://172.16.214.64'
const SERVER_API_PREFIX     = 'api'
const SERVER_CLIENT_ADDRESS = `${SERVER_CLIENT_IP}:${SERVER_CLIENT_PORT}`
const SERVER_API_ADDRESS    = `${SERVER_CLIENT_ADDRESS}/${SERVER_API_PREFIX}`

export default {
    SERVER_CLIENT_PORT,
    SERVER_CLIENT_IP,
    SERVER_CLIENT_ADDRESS,
    SERVER_API_ADDRESS
}